[package]
name = "git-warp"
version = "0.1.0"
edition = "2024"
authors = ["Git-Warp Contributors"]
description = "High-performance, UX-focused Git worktree manager combining CoW speed with advanced features"
license = "MIT"
repository = "https://github.com/your-org/git-warp"
readme = "README.md"

[[bin]]
name = "warp"
path = "src/main.rs"

[dependencies]
# CLI & TUI
clap = { version = "4.5.4", features = ["derive", "env"] }
ratatui = "0.26.2"
crossterm = "0.27.0"

# Core Logic
gix = "0.62.0"
nix = { version = "0.28.0", features = ["fs"] }
rayon = "1.10.0"
ignore = "0.4.22"
sysinfo = "0.30.12"
notify = "6.1.1"

# Configuration & Data
figment = { version = "0.10.19", features = ["toml", "env"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
toml = "0.8.13"

# Utilities
anyhow = "1.0.86"
thiserror = "1.0.61"
log = "0.4.21"
env_logger = "0.11.3"
dirs = "5.0.1"
chrono = "0.4.38"

[dev-dependencies]
tempfile = "3.10.1"
criterion = "0.5"
rand = "0.8"

[[bench]]
name = "performance_benchmarks"
harness = false
